<a href="https://colab.research.google.com/github/tharusha9009/PyTorch-Tutorials/blob/main/Pytorch_Fundemenentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [1]:
## 00.PyTorch Fundementals
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.6.0+cu124


## Introduction to tensors
# Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX =torch.tensor([[7,8],[9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors
why random tensors ?

Random tensors are important because the way many neural networks learn is that start with tensors full of random numbers and then adjust those rando, numbers to better represent the data .

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors- :https://docs.pytorch.org/docs/2.7/generated/torch.rand.html


In [ ]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1982, 0.1507, 0.5883, 0.3290],
        [0.7650, 0.9948, 0.3912, 0.0529],
        [0.0023, 0.1320, 0.4596, 0.4234]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
# Create a random tesnsor of size(2,4,5)
random_tensor_2 = torch.rand(2,4,5)
random_tensor_2

tensor([[[0.4590, 0.6115, 0.9445, 0.0175, 0.1033],
         [0.3272, 0.5939, 0.9607, 0.8429, 0.0909],
         [0.6466, 0.6882, 0.6528, 0.9456, 0.5448],
         [0.0693, 0.5966, 0.7151, 0.8569, 0.3381]],

        [[0.2774, 0.0393, 0.8881, 0.4106, 0.2963],
         [0.1664, 0.3237, 0.0269, 0.6308, 0.4240],
         [0.0409, 0.9819, 0.3409, 0.6196, 0.6581],
         [0.8734, 0.4734, 0.7143, 0.6830, 0.6817]]])

In [ ]:
random_tensor_2.ndim

3

In [ ]:
random_tensor_2.shape

torch.Size([2, 4, 5])

In [ ]:
random_image_size_tensor2=torch.rand(size=(224,224,3))
random_image_size_tensor2.shape,random_image_size_tensor2.ndim

(torch.Size([224, 224, 3]), 3)

### Creating tensors With Zeros And Ones in PyTorch


In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype
zeros.dtype

torch.float32

### Creating a tensor range and tensors like other tensors

In [ ]:
# Use torch.arange()
torch.arange(0,10,2)


tensor([0, 2, 4, 6, 8])

In [ ]:
# Creating tensors like
ten_Zeros = torch.zeros_like(input=torch.arange(0,10))
ten_Zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
**Note:** Tensor datatype is one of the 3 big erros you'll run into woth PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                                              device=None,# what device is your tensor on
                                              requires_grad=False) # Whether or not to track gradients withy this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensor (Tensor Attributes)
1. Tensors not right datatype - to do get datatype from a tensor , can use `tensor.dtype`

2. Tensors not right shape - to get shape from a tensor , csn use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor , can use `tensor.device`


In [ ]:
# Create a Tensor
some_tensor = torch.rand(3,4)
some_tensor


tensor([[0.2967, 0.1171, 0.9375, 0.9951],
        [0.1722, 0.1922, 0.0396, 0.0191],
        [0.0906, 0.0841, 0.5481, 0.7171]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Devicr tensor is on : {some_tensor.device}")

tensor([[0.2967, 0.1171, 0.9375, 0.9951],
        [0.1722, 0.1922, 0.0396, 0.0191],
        [0.0906, 0.0841, 0.5481, 0.7171]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Devicr tensor is on : cpu


### Manipulating Tensors
Tensor operation include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication


In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor=tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor = tensor -10
tensor

tensor([ 0, 10, 20])

In [ ]:
# Try out PyTorch in  built functions
torch.mul(tensor,10)


tensor([  0, 100, 200])

In [ ]:
torch.add(tensor,10)


tensor([10, 20, 30])

### Matrix mutiplication
Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise multiplication.
2. Matrix mutliplication.
There are two main rules that performing matrix multiplication needs to satisfy:
  1.  The `inner dimensions ` must match:
  * (3,2) @ (3,2) won't work
  * (2,3) @ (3,2) will work
  * (3,2) @ (2,3) will work
  2.  The resulting matrix has the shape of the `Outer dimensions `:
  * (2,3) @  (3,2 ) -> (2,2)
  * (3,2) @  (2,3)  -> (3,3)
  


In [ ]:
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])

In [ ]:
# Element wise multiplication
print(tensor,"*", tensor)
print(f"Equals :{tensor * tensor}")

tensor([ 0, 10, 20]) * tensor([ 0, 10, 20])
Equals :tensor([  0, 100, 400])


In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)


tensor(500)

In [ ]:
tensor

tensor([ 0, 10, 20])

In [ ]:
# Matrix multiplication by  hand
1*1+2*2+3*3

14

In [ ]:
%%time
value =0
for i in range(len(tensor)):
  value+= tensor[i]+tensor[i]
print(value)


tensor(60)
CPU times: user 1.02 ms, sys: 0 ns, total: 1.02 ms
Wall time: 945 µs


### One of the most common errors in deep learning: shape errors


In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# torch.mm(tensor_A , tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
print(f"Tensor A shape : {tensor_A.shape} \nTensor B shape : {tensor_B.shape}")


Tensor A shape : torch.Size([3, 2]) 
Tensor B shape : torch.Size([3, 2])


In [ ]:
print(f"Tensor B :{tensor_B} \nTensor B shape : {tensor_B.shape}")

Tensor B :tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]) 
Tensor B shape : torch.Size([3, 2])


In [ ]:
print(f"Tensor B Transpose : {tensor_B.T} \nTensor B shape : {tensor_B.T.shape}")

Tensor B Transpose : tensor([[ 7,  8,  9],
        [10, 11, 12]]) 
Tensor B shape : torch.Size([2, 3])


In [ ]:
# The matrix multiplication operation  work when tensor_B is transposed.
print(f"Original shapes : {tensor_A.shape} Tensor B shape : {tensor_B.shape}")
print(f"New shapes : {tensor_A.shape} Tensor B shape : {tensor_B.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output :\n")
output = torch.matmul(tensor_A , tensor_B.T)
print(output)
print(f"\nOutput shape : {output.shape}")

Original shapes : torch.Size([3, 2]) Tensor B shape : torch.Size([3, 2])
New shapes : torch.Size([3, 2]) Tensor B shape : torch.Size([3, 2])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
Output :

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape : torch.Size([3, 3])


### Finding the min , max , mean , sum , etc (tensor aggregation)


In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean - note : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x) , x.sum()


(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x1= torch.arange(1,100,10)
x1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin ()-> returns index position of target position of target tensor where the minimum value occurs
x1.argmin()

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum  value with argmax()
x1.argmax()


tensor(9)

## Reshaping , stacking , squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking -  combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - removes all dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped)in a certain way .


In [ ]:
# Lets create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on the top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Prevoius tensor : {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"\nNew Shape : {x_squeezed.shape}")



Prevoius tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New Shape : torch.Size([9])


In [ ]:
 # torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Prevous target : {x_squeezed}")
print(f"Prevous shape : {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")


Prevous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Prevous shape : torch.Size([9])

New tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a traget tensor in a specified order
x_original = torch.rand(size=(224 , 224 ,3)) # [height , width , color_channels]

# Permute the original tensor to rearrange the axix (or dim ) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0-> 1 , 1-> 2 , 2 ->0

print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}") # [color_channels , height , width]




Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


### Indexing with PyTorch is similar to indexing with NumPy

In [3]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim =1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][1][2]

tensor(6)

In [ ]:
# You can also use ": " to select "all"of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,: ,1]


tensor([[2, 5, 8]])

In [ ]:
# Get all the values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dimension  and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [4]:
# Index on x to return 9
print(x[0][2][2])
# Index on x to return 3,6,9
print(x[:,:,2])


tensor(9)
tensor([[3, 6, 9]])
